table Medidas
	lineageTag: 4be8bfbe-ac2d-4f83-8351-b7adec4ab5d8

	measure 'Soma Qtd' = Sum(TF_PEDIDOS[Quantidade])
		formatString: 0
		lineageTag: e8bc2068-db34-4d62-899b-7a2d376d46c7

	measure 'Média Vendas' = AVERAGEX(TF_PEDIDOS,TF_PEDIDOS[Quantidade]* TF_PEDIDOS[Preço Unitário])
		lineageTag: ca57056b-3f91-491f-a159-1330c5207fc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Pedidos' = DISTINCTCOUNT(TF_PEDIDOS[Código do Pedido])
		formatString: 0
		lineageTag: 7f120193-4960-43ba-ad2f-d2693154dda8

	measure 'Soma Metas' = SUM(TF_METAS[Valor])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 442f05c3-a0e1-41e9-aac7-6113a8d5ab94

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Soma Vendas' = SUMX(TF_PEDIDOS,TF_PEDIDOS[Quantidade]* TF_PEDIDOS[Preço Unitário])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d1b2c127-e03e-447a-abb8-d867f76c441a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Maior Venda' = MAXX(TF_PEDIDOS,TF_PEDIDOS[Quantidade]* TF_PEDIDOS[Preço Unitário])
		formatString: 0
		lineageTag: 639d0f4a-cddc-4396-9754-9d3ae0229675

	measure 'Menor Venda' = MINX(TF_PEDIDOS,TF_PEDIDOS[Quantidade]* TF_PEDIDOS[Preço Unitário])
		formatString: 0
		lineageTag: 97a346cd-28f8-40d9-9a25-42b189b6427f

	measure '% Vendas VS Metas' = [Soma Vendas]/[Soma Metas]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e40fb457-c5e1-40c1-803f-87c6a8ad3eb4

	measure 'Soma qtd SP' = CALCULATE([Soma Qtd],TD_LOJA[UF]=="SP")
		formatString: 0
		lineageTag: f1a345b5-fe51-4a70-af76-15c5366c082d

	measure '% sobre SP' = DIVIDE([Soma Qtd],[Soma qtd SP])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 99bd1f42-891f-4875-a11f-05a842aaedd4

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: a7d44238-ad0f-4cb6-ae80-2521305bfed9
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

